[book]
authors = ["TrackAsia Contributors"]
language = "en"
multilingual = false
src = "src"
title = "TrackAsia Native Developer Documentation"

[output.html]
additional-css = ["diff.css"]

[preprocessor.alerts]
